### ISSUE TITLE
Links are not being followed

### ISSUE THREAD

**Issue by PetaPetaPeta** [scrapinghub/distributed-frontera#14]
I have a setup that follows the one described in the quickstart documentation(http://distributed-frontera.readthedocs.org/en/latest/topics/quickstart.html). Everything is set up and seems to be running. I have created my own seed list with four sources to make it easier to skim through the logs.
When I start the crawler it does not seem to be following any links. I have extracted a small portion of the logs for each element below.

DB worker:
	http://pastebin.com/iczintmR

DB worker after starting the spider:
	http://pastebin.com/LBW4DFyu

Strategy worker:
	http://pastebin.com/pk7ygjM3

Spider:
	http://pastebin.com/eSG4QVSm

I can only see one thing that looks suspicious. That is the log of the spider which contains some long lines that end with `..e\n\x01<\xaescrapy_errback\xc0')])]`.

What could be wrong here?

**Comment by sibiryakov** [comment]
Hey @PetaPetaPeta! It seems your spider isn't sending extracted links to the strategy worker. As I see messages extracted in Kafka log, should contain urls of extracted links, and they aren't there. Before repeating this don't forget to clean your HBase storage or somehow reset the states of your seeds.

**Comment by PetaPetaPeta** [comment]
Hello @sibiryakov. Thanks for getting back to me! 
I am not quite certain what it is I should repeat. Can you be more explicit? I am creaning the storage of HBase using HBASE_DROP_ALL_TABLES in workersettings.py - is that enough?

**Comment by sibiryakov** [comment]
@PetaPetaPeta Yes, that's enough. I meant when you re-run workers, and running spiders again with seeds source you basically retrying your previous crawl attempt.

**Comment by PetaPetaPeta** [comment]
Hi @sibiryakov 

I have now emptied both the kafka topics and the HBase tables. To empty the Kafka topics I ran the following set of commands for each topic:
    /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic {TOPIC-name} - -config retention.ms=1000
    wait a few seconds
    /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic frontier-score - -config retention.ms=86000000

I also ran the following command to watch the topic `frontier-todo` in Kafka as it got updated:
    /opt/kafka/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic frontier-todo

After I did this it seemed to work correctly. I am not sure about what changed, but it seems to function now. Thank you for helping me.

**Comment by sibiryakov** [comment]
@PetaPetaPeta That's happening because of some bug with negative lags. Would be nice to investigate it.

**Comment by PetaPetaPeta** [comment]
@sibiryakov So that is what I can see in the DB worker log after starting the spider right?

I am currently implementing a FIFO strategy as naive strategy. Would a correct approach be to reuse the BFS strategy, but simply replace the `get_score` function with a function that returns the current timestamp?

**Comment by PetaPetaPeta** [comment]
Btw - I think the negative lag might either have something to do with me changing the seeds file after I had data in HBase and Kafka, or me clearing Kafka without clearing HBase.

**Comment by sibiryakov** [comment]
@PetaPetaPeta Yes, you see these negative lags when you start. Lags should be adequate in order to produce new batches in DB worker. Sometimes when you add more message to the topic, lags are increasing, but still negative. There is definitely a bug somewhere in Kafka broker or client. I was deleting topics to fix this. It's independent from HBase, and I dont think it's connected with seeds file.

**Comment by sibiryakov** [comment]
Reopen this, if you want to investigate that.

**Comment by sibiryakov** [comment]
Regarding FIFO, I think not. You should get FIFO by using always some fixed score value, say ``0.0``.
