### ISSUE TITLE
Documentation and error messages for system configuration

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/distributed-frontera#15]
I have installed Kafka and HBase on my system and set up everything according to the Quickstart guide.

During installation I noticed some error's/missing content in your documentation. This is what I did differently from the official docs:
 * HBase and Kafka should at least be installed in pseudo-distributed mode (I hope that is true and maybe you should mention that for total beginners like me ;) )
 * Thrift for python is a requirement
 * I had to create a namespace in HBase for it to work
 * Also:
```
scrapy crawl general -L INFO -s FRONTERA_SETTINGS=frontera.spider0 -s SEEDS_SOURCE=seeds_es_dmoz.txt
scrapy crawl general -L INFO -s FRONTERA_SETTINGS=frontera.spider1
```
should be
```
scrapy crawl general -L INFO -s FRONTERA_SETTINGS=frontier.spider0 -s SEEDS_SOURCE=seeds_es_dmoz.txt
scrapy crawl general -L INFO -s FRONTERA_SETTINGS=frontier.spider1
```

Following your Quickstart guide till the end I now had one DB worker and two strategy workers running. The tables 'crawler:metadata' and 'crawler:queue' had been created. However they did not send any messages to the Kafka topics or print out any message about websites being crawled.

Using the worker_settings.py and settingsN.py from your production settings, I am able to produce more output and I am able to see messages in the 'frontier:done' topic. But the other kafka topics and tables in HBase are still empty.
```
hbase(main):027:0> count 'crawler:metadata', INTERVAL=> 1
0 row(s) in 0.0060 seconds

=> 0
```

However there are no error messages that something could be wrong.

I also found the scrapy_project on github and I tried updating my pyhton kafka and distributed frontera to the latest github version. Running that had the same effect.

Sorry for reporting an issue which is more like a configuration issue on my side than an issue in your code. But fixing this would help other users to install it more quickly.

**Comment by sibiryakov** [comment]
Hi! I do value your feedback on documentation, it's not ideal for sure. You could create a pull request, in order to improve it.

Please make sure that ``add_seeds`` events are propagated to SW, SW issue ``update_score`` event and it's received by DB worker, and finally DB worker is creating new batch with URL from initial ``add_seeds``.  If not, the first place to look is Kafka consumer groups offsets, all consumers do check these offsets and decide if there are new messages to consume.

If not, please post your configs and DB/SW workers output in full, after running them for few minutes. 

A.

**Comment by lljrsr** [comment]
Hi.

Thanks for your fast reply. It's working now! And it is fast too :+1:  . I think the problem was that distributed frontera did not want to use the Kafka Backend and MessageBus, default host and port by default. Strangely I also had to set SCORING_TOPIC = 'frontier-score'.

Here are the files that I changed in your github project "general-spider":
http://pastebin.com/xHztszvC
http://pastebin.com/uffK1F3L

If you think that my changes are correct, you could update the "general-spider" github project, so other users won't have this problem.

If I find the time I will make a push request to update the docs.

Thanks

Joris

**Comment by sibiryakov** [comment]
You're welcome!

**Comment by sibiryakov** [comment]
Regarding spider_settings.py file, I would recommend to add ``MESSAGE_BUS`` line, instead of changing backend.

**Comment by lljrsr** [comment]
If I do that no seeds will be added, no messages get sent to kafka-todo and the crawler:metadata stays empty.

The DW keeps writing:
```
[db-worker] Getting new batches for partitions 0,1
[backend] Querying queue table.
[backend] Try 1, limit 64, last attempt: requests 0, hosts 0
[backend] Try 2, limit 352, last attempt: requests 0, hosts 0
[backend] Try 3, limit 1936, last attempt: requests 0, hosts 0
[backend] Finished: tries 3, hosts 0, requests 0
[backend] 0 row keys removed
[backend] Got 0 items for partition id 0
[backend] Try 1, limit 64, last attempt: requests 0, hosts 0
[backend] Try 2, limit 352, last attempt: requests 0, hosts 0
[backend] Try 3, limit 1936, last attempt: requests 0, hosts 0
[backend] Finished: tries 3, hosts 0, requests 0
[backend] 0 row keys removed
[backend] Got 0 items for partition id 1
[db-worker] Pushed new batch of 0 items
No handlers could be found for logger "kafka.consumer.simple"
[db-worker] Consumed 0 items.
[db-worker] Consumed 0 items during scoring consumption.
```
And the SW keep writing:
```
[backend] cache size 0
[backend] to fetch 0 from 0
[strategy-worker] Consumed 0 items.
```

**Comment by lljrsr** [comment]
Actually using the general_spider without kafka is working just fine. My mistake was that I followed your documentation on http://distributed-frontera.readthedocs.org/ and not on this repo.

**Comment by sibiryakov** [comment]
It would be nice to find out why Kafka message bus doesn't work. Could you post your settings files?

**Comment by lljrsr** [comment]
Actually the MESSAGE_BUS setting does not change anything in spider_settings.py . I can set it to "asdf" and there is no error message that anything is wrong. I can also choose a settings variable that does not exist. There is still no error message.

Here are the settings files:
http://pastebin.com/zF8p7JrN
http://pastebin.com/9aKuecGw
http://pastebin.com/jjChw3UF

**Comment by sibiryakov** [comment]
I don't see your strategy worker settings. And this file is used what for http://pastebin.com/zF8p7JrN ? ``MESSAGE_BUS`` should be used for all components: SW, DB, and spiders. You have to make sure, this setting is read by each component. SW and DB do use separate settings files.

**Comment by lljrsr** [comment]
Sorry, I forgot to set a title for the first file. The untitled file you mentioned is my workersettings.py . The files are mainly the same as the ones from general_spider repo. I have set the MESSAGE_BUS setting in both settings files (as you can see).

**Comment by sibiryakov** [comment]
Is there any progress on this? Did you managed to get message bus to work?

**Comment by lljrsr** [comment]
I have switched to zeromq now, therefore I did not try to fix any Kafka related issues. If you want to reproduce the issue just clone the general_spider repo and use the settings files I posted here.

**Comment by sandeepsingh-innoplexus** [comment]
facing issue with :
TypeError: Can't instantiate abstract class HBaseBackend with abstract methods finished

when i ran this:
python -m distributed_frontera.worker.main --config frontier.workersettings

**Comment by sandeepsingh** [comment]
Facing issue with Distributed frontera: TypeError: Can't instantiate abstract class HBaseBackend with abstract methods finished

python -m distributed_frontera.worker.main --config frontier.workersettings

**Comment by sibiryakov** [comment]
Hey @sandeepsingh-innoplexus and @sandeepsingh the distributed frontera is outdated and was merged to original frontera, please run workers from frontera module.

**Comment by sandeepsingh** [comment]
Well, still getting the same error with frontera installation,
and after running this command,

python -m frontera.worker.db --config frontier.workersettings

ERROR:-
  return cls.from_manager(self)
  File "lib/python2.7/site-packages/distributed_frontera/backends/hbase.py", line 341, in from_manager
 return cls(manager)
TypeError: Can't instantiate abstract class HBaseBackend with abstract methods finished

**Comment by sibiryakov** [comment]
what frontera version you're using? have you tried latest master?

**Comment by sandeepsingh** [comment]
i did pip install frontera, version is frontera==0.5.3.

**Comment by sandeepsingh** [comment]
Hi, 
i want to put my raw data into hdfs is there already some backend/pipeline written for it. Please help me on this.

**Comment by sibiryakov** [comment]
Hi,
Probably your config has references to distributed_frontera module, resp. Hbase backend.

If you want to put frontera database to hdfs then the easiest way to do it is to first run crawler using hbase and then write a map reduce job with output to hdfs.

Отправлено с iPhone

**Comment by sandeepsingh** [comment]
Thanks @sibiryakov  first issue got resolved. i was running the wring example folder in general siper. 

Regarding storage, how to make crawler store raw html in hbase backend as of now as i see it only stores metadata into the hbase backend.

**Comment by sandeepsingh** [comment]
Hi sibiryakov,
I am getting new error while i configured my workersettings.py to run on Hbase backend. 

error is:
happybase.connection Closing Thrift transport to localhost:9090

**Comment by sibiryakov** [comment]
It says pretty clearly that it lacks of namespace, and it needs to be created in HBase.
I would recommend to ask this questions in the mailing list, since this ticket isn't intended for this.
