### ISSUE TITLE
HBASE_STORE_CONTENT not working properly

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/distributed-frontera#17]
Saving content directly in HBase does not work right now.
Setting `HBASE_STORE_CONTENT=True` in the settings file creates the necessary rows and column family. However the values are always empty. After debugging I found out that `response.body` is None in these lines in [the HBase Backend](https://github.com/scrapinghub/distributed-frontera/blob/70e9d652928aaaecc89f06f51cee97b0ec2148a5/distributed_frontera/backends/hbase.py#L360) and [the worker](https://github.com/scrapinghub/distributed-frontera/blob/master/distributed_frontera/worker/main.py#L111). Also setting `send_body=True' when creating all of the Encoders does not seem to change that. I was not able to debug the cause.

**Comment by sibiryakov** [comment]
Hi @lljrsr it seems it's isn't send by spiders. Can you try debugging in MessageBusBackend/KafkaBackend ?

**Comment by lljrsr** [comment]
I already tried debuggin MessageBusBackend.
`__init__` of `MessageBusBackend()` is not being called altough I set `BACKEND = 'distributed_frontera.backends.remote.messagebus.MessageBusBackend'` in my spider_settings.py file.

**Comment by sibiryakov** [comment]
This is quite strange. Without __init__ call there is no way to perform for MessageBusBackend correctly. Setting Encoders ``send_body`` to ``True`` is a minimum requirement, without that it wouldn't work for sure. And this should enable sending content over the message bus.

Next thing to make sure the data is propagated from DB worker to HBaseBackend and stored in HBase.

**Comment by lljrsr** [comment]
Yes all the data is being stored in HBase. Only the values of the content is always `None`.. since the HTML body is also `None`.
In which file should the `MessageBusBackend()` get initialized when I run my spider? ..I cannot seem to find it.

**Comment by lljrsr** [comment]
Okay. I think it was my own mistake. Will test a bit further and close if that really was the case. Thanks for your fast reply!! :+1:

**Comment by sibiryakov** [comment]
It's here https://github.com/scrapinghub/frontera/blob/master/frontera/core/manager.py#L24
NP!

**Comment by lljrsr** [comment]
Thanks! I opened a pull request.

**Comment by sibiryakov** [comment]
Can we close this?

**Comment by lljrsr** [comment]
Yes. Everythin is working now.
