### ISSUE TITLE
Style change destroyed settings for crawler

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/distributed-frontera#21]
Hi.

Using your latest commit on [this file](https://github.com/scrapinghub/distributed-frontera/blob/master/distributed_frontera/settings/__init__.py) no attributes are being propagated to the Settings class any longer. This means in [here](https://github.com/scrapinghub/distributed-frontera/blob/master/distributed_frontera/backends/remote/messagebus.py#L12) the default settings will always be used.
This means the spiders will always use the default settings.
I do not know a nice way to fix this. But it looks like it could be easily fixed ;) .

**Comment by lljrsr** [comment]
..okay I fixed it anyway :wink: .

**Comment by sibiryakov** [comment]
Yes, there is a bug!

**Comment by lljrsr** [comment]
Fixed with d404ab9
