### ISSUE TITLE
Missing messages

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/distributed-frontera#24]
One of my spiders throws this error message every now and then. I could not find any information in your docs about it. How do I check for missing messages? What is a good way to debug the cause?
```
2015-12-30 17:09:38 [distributed_frontera.messagebus.zeromq.Consumer(sf-1)] WARNING: Sequence counter mismatch: expected 68083, got 68166. Check if system isn't missing messages.
```

**Comment by sibiryakov** [comment]
Yes, this definitely needs to be covered in documentation. There is no clear way how to solve it, the problem goes into ZeroMQ internals. Somehow your DB worker generated too much messages for your message bus. Consumer SF-1 stands for `spider feed` partition 1. ZeroMQ stores messages in memory in fixed size queues, when these queues overflow it starts to drop the messages. When you see such warning it means, spider detected that messages are missing.

There are few ways how to solve it:
 - Try to fit your DB worker `MAX_NEXT_REQUESTS` setting (the number of messages it produces to `spider feed` for one batch) and spiders consumption rate. Ideally would be to avoid any excessive amount of messages to be hold in transport layer.
 - If you think previous is OK, and you need to buffer bigger queues then try increasing at https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/messagebus/zeromq/__init__.py#L207 and next line.

If you go for second approach please let me know why.

**Comment by lljrsr** [comment]
I already opened up an issue because I am a bit confused about the correct configuration for MAX_NEXT_REQUESTS. So this will most likely be the cause. I will try to change that.

**Comment by lljrsr** [comment]
After fixing the HBase Backend issue, it seems that my crawler is still having the same issues.
I have configured those values:
```
CONCURRENT_REQUESTS = 64
 
# Worker
MAX_NEXT_REQUESTS = 448

# Spider
MAX_NEXT_REQUESTS = 224
```
..after about one hour my spider keeps printing out the warnings every 2-4 minutes. Do you still think that this is only due to the fact that my spider is consuming less than what my DW is pushing?

**Comment by sibiryakov** [comment]
You should have stats in spider, counting how much it is consuming. Please post them

**Comment by lljrsr** [comment]
Alright. I will collect some data. You are talking about [this line](https://github.com/scrapinghub/frontera/blob/60747efda360429dc1258ede635e762c635193a8/frontera/core/manager.py#L463) right?

**Comment by sibiryakov** [comment]
Yes, also Scrapy has it's own statistics.

**Comment by sibiryakov** [comment]
ZeroMQ broker has stats too.

**Comment by lljrsr** [comment]
Which stats are you referring to?

**Comment by sibiryakov** [comment]
Regarding ZeroMQ broker it outputs the amounts of passed messages through it. Scrapy collects internally stats using http://doc.scrapy.org/en/latest/topics/stats.html and by default outputs it at spider shutdown.

**Comment by lljrsr** [comment]
Okay thanks :smile: . I will tell you whenever the warning appears again. I am playing around with my configuration right now. It seems to work with a low `MAX_NEXT_REQUESTS` setting for the DW.

**Comment by sibiryakov** [comment]
It would be nice if you could try debugging it. This is the first such experience outside of Scrapinghub, so I'm interested. When I was designing it, I planned that user will notice message, or wrong crawler behavior and then start to investigate. Basically stats from different places should fit, but I never checked that, would be nice if someone could do this.

**Comment by lljrsr** [comment]
The problem seems to have disappeared.

**Maybe a bit off-topic, but maybe related**
Another issue I noticed recently is that my DW keeps on pushing to all partitions although I have no spider running. When I start up my spiders now, they wait until the DW has pushed a new batch (although he pushed multiple times before that). This means that after running the DW for a while without there being any spider running depletes the queue until there is nothing left to crawl. I have to add new seeds (not the same seed URLs, since multiples get dropped) for the spiders to start again and the DW to push new requests again.
But this is not a very bad issue for me right now (it may be in a few weeks or so, though) and this particular issue #24 seems to be resolved. It would still be nice if this depletion of the queue by the DW could be fixed in a future release.

**Comment by sibiryakov** [comment]
Great that you solved that. Let's discuss further in separate issue!
