### ISSUE TITLE
frontera merged with distributed-frontera?

### ISSUE THREAD

**Issue by lljrsr** [scrapinghub/distributed-frontera#25]
I have just seen that the functionality of distributed-frontera is now also available in frontera. Will this repo be maintained separately? Is it a good idea for distributed-frontera users to start using only the frontera repo?

**Comment by sibiryakov** [comment]
This repo will not be maintained separately, yes it's a good idea to start using only Frontera *package* (it's available in pip). Master branch in repo isn't always stable.
Consider also subscribing to Frontera mailing list https://groups.google.com/a/scrapinghub.com/forum/#!forum/frontera.
